#!/bin/sh

source "`dirname $0`/utils/defs.sh"

FULLCLEAN="$1"

case "$1" in
  # Specific
  bin|binutils)
    msg "Removing binutils build dir"
    rm -rf "$OBJDIR/binutils"
    exit
    ;;
  pdc|pdclib)
    msg "Removing pdclib build dir"
    rm -rf "$OBJDIR/pdclib"
    exit
    ;;
  core|teensy|teensy-core)
    msg "Removing teensy-core build dir"
    rm -rf "$OBJDIR/teensy-core"
    exit
    ;;

  # Dir-specific
  distfiles)
    msg "Removing distfiles dir"
    rm -rf "$DISTFILES"/*
    exit
    ;;
  build)
    msg "Removing build dir"
    rm -rf "$OBJDIR"
    exit
    ;;
  prefix|install)
    msg "Removing prefix dir"
    rm -rf "$PREFIX"
    exit
    ;;
  src)
    msg "Removing src dir"
    rm -rf "$SRCDIR"
    exit
    ;;

  --full)
    # skip. To be dealt with later.
    ;;
  # Default case
  *)
    if [ ! -z "$1" ]; then
      # die if we didn't understand the argument
      die "Don't know how to clean $1"
    fi
    ;;
esac

msg "Removing build dir"
rm -rf "$OBJDIR"

if [[ "$FULLCLEAN" = "--full" ]]; then
  msg "Removing prefix dir and distfiles"
  rm -rf "$PREFIX" "$DISTFILES"
fi
