#!/bin/sh

source "`dirname $0`/utils/defs.sh"

FULLCLEAN="$1"

if [[ "$FULLCLEAN" = "--full" ]]; then
  msg Removing installed files and distfiles
  rm -rf arm-none-eabi distfiles
fi

msg Removing build directory
rm -rf build
